---

- name: install mysql server
  yum:
    name: "{{ mysql['pkg']['server'] }}"
    update_cache: yes
  when: mysql.server
  
- name: install mysql python binding
  yum:
    name: "{{ mysql['pkg']['python'] }}"
    