# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.box = "ubuntu/trusty32"

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.168.10"
  end

  config.vm.define "dbel" do |dbel|
    dbel.vm.box = "puppetlabs/centos-6.6-32-nocm"
    dbel.vm.hostname = "dbel"
    dbel.vm.network "private_network", ip: "192.168.168.11"
  end

  config.vm.define "www" do |www|
    www.vm.box = "ubuntu/trusty64"
    www.vm.hostname = "www"
    www.vm.network "private_network", ip: "192.168.168.12"
  end

  config.vm.define "lb" do |lb|
    lb.vm.hostname = "lb"
    lb.vm.network "private_network", ip: "192.168.168.13"
  end

end

